export const VISIBILITY_STATUS = {
    SHOW_ALL: "SHOW_ALL",
    SHOW_PENDING: "SHOW_PENDING",
    SHOW_COMPLETED: "SHOW_COMPLETED"
}
export const TASK_STATUS = {
    PENDING: "PENDING",
    COMPLETED: "COMPLETED"
}
export const TODO_SLICE_NAME = "todo";